xcopy "%GIANTS_PATH%\gg_dx7r.dll" "Files\" /Y
xcopy "%GIANTS_PATH%\gg_dx9r.dll" "Files\" /Y
xcopy "%GIANTS_PATH%\Giants.exe" "Files\" /Y
xcopy "%GIANTS_PATH%\GiantsMain.exe" "Files\" /Y
xcopy "%GIANTS_PATH%\GiantsDedicated.exe" "Files\" /Y
xcopy "%GIANTS_PATH%\gs_ds.dll" "Files\" /Y
xcopy "%GIANTS_PATH%\Giants.WebApi.Clients.dll" "Files\" /Y
xcopy "%GIANTS_PATH%\fmt.dll" "Files\" /Y
xcopy "%GIANTS_PATH%\BugTrap.dll" "Files\" /Y
xcopy "%GIANTS_PATH%\cpprest_2_10.dll" "Files\" /Y
xcopy "%GIANTS_PATH%\Newtonsoft.Json.dll" "Files\" /Y
xcopy "%GIANTS_PATH%\zlib1.dll" "Files\" /Y